POST http://localhost:3003/api/blogs/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1hcmsgRG9lIiwiaWQiOiI2NmIyMTlhN2ExZjMyNTU2Y2U1NGJkZDEiLCJpYXQiOjE3MjI5NDgyNTUsImV4cCI6MTcyMjk1MTg1NX0.x_rLvEC4tfBZ2RDJ79Wqd5sssejWuLHLIeq_d9dB8DU
{
    "title": "Blog123",
    "author": "Author123",
    "url": "MyBlog.com123",
    "likes": "1"
}